# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['SWIFT_VERSION'] = "4.0"
        end
    end
end


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
def shared_pods
# Add pods here
pod 'Alamofire'

end

  # Pods for Test
target 'Test' do
 shared_pods
end
